# Focus
static/css/*
static/js/*
# config.py
app/routes/portfolio*
# app/utils/formatting.py
app/utils/db_utils.py
app/utils/portfolio_utils.py
templates/pages/allocate.html
templates/pages/build.html
templates/pages/analyze.html
templates/components/analyse_components.html
#templates/pages/build.html
#templates/pages/enrich.html
#templates/pages/index.html
#templates/base.html

# Exclude
_*/
.*/
venv/
env/