# Focus
static/css/*
static/js/*
templates/pages/build.html
#templates/pages/analyze.html
#templates/components/analyse_components.html
templates/pages/allocate.html
#templates/pages/enrich.html
#templates/pages/index.html
#templates/base.html

# Exclude
_*/
.*/
venv/
env/