services:
  portfolio-app:
    build: .
    container_name: portfolio_rebalancer
    restart: unless-stopped
    ports:
      - "8065:8065"
    volumes:
      # Create and mount local data directory for persistence
      - ./data:/data
      # Mount environment file
      - ./.env:/app/.env:ro
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:////data/database/portfolio.db
    labels:
      # Enable autoheal monitoring
      - "autoheal=true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8065/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge