services:
  portfolio-app:
    build: .
    container_name: portfolio_rebalancer
    restart: unless-stopped
    ports:
      - "8065:8065"  # Main application port
    volumes:
      # Mount app/database directory for persistence
      - ./app/database:/app/database
      # Mount environment file
      - ./.env:/app/.env:ro
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///app/database/portfolio.db
    labels:
      # Enable autoheal monitoring
      - "autoheal=true"
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge