services:
  portfolio-app:
    build: .
    container_name: portfolio_rebalancer
    restart: unless-stopped
    ports:
      - "8065:8065"  # Main application port
    volumes:
      # Mount instance directory for all persistent data
      - ./instance:/app/instance
      # Mount environment file
      - ./.env:/app/.env:ro
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///app/instance/portfolio.db
    labels:
      # Enable autoheal monitoring
      - "autoheal=true"
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge